# Generated by Django 3.2.4 on 2021-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['created'], 'verbose_name': 'Cabañas', 'verbose_name_plural': 'RegistroCabañas'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=12),
        ),
    ]
