# Generated by Django 3.2.4 on 2021-08-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_promociones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabañas',
            name='numCamas',
            field=models.TextField(verbose_name='Número De Camas'),
        ),
        migrations.AlterField(
            model_name='cabañas',
            name='numPersonas',
            field=models.TextField(verbose_name='Número De Personas Por Cabaña'),
        ),
    ]
