# Generated by Django 3.2.4 on 2021-08-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20210823_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabañas',
            name='id',
        ),
        migrations.AlterField(
            model_name='cabañas',
            name='clave',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField()),
                ('fechaCrea', models.DateTimeField(auto_now=True)),
                ('fechaEnt', models.DateField(verbose_name='Fecha de entrada')),
                ('fechaSal', models.DateField(verbose_name='Fecha de salida')),
                ('estado', models.IntegerField(default=1, help_text='Tomada 0, En espera 1', verbose_name='Estado')),
                ('num_a', models.IntegerField(verbose_name='Numero de adultos')),
                ('num_n', models.IntegerField(null=True, verbose_name='Numero de niños')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cabañas', verbose_name='Habitacion')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
