# Generated by Django 3.2.4 on 2021-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20210824_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaciones',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='reservaciones',
            name='estado',
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='num_a',
            field=models.IntegerField(max_length=30, verbose_name='Numero de adultos'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='num_n',
            field=models.IntegerField(max_length=5, null=True, verbose_name='Numero de niños'),
        ),
    ]
