# Generated by Django 3.2.4 on 2021-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20210824_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaciones',
            name='num_a',
            field=models.IntegerField(verbose_name='Numero de adultos'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='num_n',
            field=models.IntegerField(null=True, verbose_name='Numero de niños'),
        ),
    ]
